name: Update Glossary

on:
  push:
    branches:
      - main
    # paths:
    #   - "docs/*.md"  # Qualquer mudança em .md na pasta docs
  workflow_dispatch:  # Permite rodar manualmente, se desejar

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixando o repositório com histórico completo
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Traz o histórico completo para detecção de mudanças

      # 2. Verificar se há mudanças em arquivos .md
      - name: Verificar alterações em arquivos .md
        run: |
          git diff --name-only HEAD^ HEAD | grep -E '^docs/.*\.md$' || echo "Nenhuma alteração relevante detectada."

      # 3. Configurando o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4. Executando o script de índice
      - name: Run glossary generation script
        run: |
          python3 bin/generate_glossary.py  

      # 5. Seta uma variável com data e hora
      - name: Set date and time
        run: |
          export TZ=America/Sao_Paulo
          DataHora=$(date "+%Y-%m-%d %H:%M:%S %z")
          echo "DataHora=${DataHora}" >> $GITHUB_ENV
      
      # 6. Altera o valor de data e hora no readme.md
      - name: Set date and time on readme.md
        run: |
          sed -i "s|\*\*Artigo atualizado em:\*\* .*|\*\*Artigo atualizado em:\*\* ${DataHora}|" README.md

      # 7. Seta uma variável com a quantidade de termos
      - name: Set amount of docs
        run: |
          MD_COUNT=$(find docs -type f -name "*.md" | wc -l)
          echo "MD_COUNT=${MD_COUNT}" >> $GITHUB_ENV
      
      # 8. Altera o valor da quantidade de termos no readme.md
      - name: Set the amount of docs on readme.md
        run: |
          sed -i "s|\*\*Total de termos:\*\* .*|\*\*Total de termos:\*\* ${MD_COUNT}|" README.md

      # 9. Preparando para commit e push
      - name: Configure git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://${{ secrets.GH_TOKEN }}@github.com/leonardopangaio/glossario.git"
          git add README.md

      # 10. Verificar arquivos adicionados (debug)
      - name: Listar arquivos preparados para commit
        run: |
          git status

      # 11. Commit e push, se houver mudanças
      - name: Commit and push changes
        run: |
          git commit -m "Atualização automática do índice no README.md" || echo "Nenhuma mudança para commit"
          git push origin HEAD:main
